<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hari" failures="1" tests="6" name="com.TestEngine.RetryAnaly" time="0.048" errors="0" timestamp="2024-05-06T15:53:29 IST" skipped="5">
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.036">
    <skipped/>
  </testcase> <!-- stringnames -->
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.002">
    <skipped/>
  </testcase> <!-- stringnames -->
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.002">
    <failure message="expected [Hariharan] but found [hariharan]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Hariharan] but found [hariharan]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.TestEngine.RetryAnaly.stringnames(RetryAnaly.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- stringnames -->
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.004">
    <skipped/>
  </testcase> <!-- stringnames -->
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.002">
    <skipped/>
  </testcase> <!-- stringnames -->
  <testcase classname="com.TestEngine.RetryAnaly" name="stringnames" time="0.002">
    <skipped/>
  </testcase> <!-- stringnames -->
</testsuite> <!-- com.TestEngine.RetryAnaly -->
